version = 1

test_patterns = ["src/tests/**", "src/specs/**"]

exclude_patterns = [".azuredevops/**", ".devcontainer/**", ".github/**", ".vscode/**", "dist/**", "node_modules/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [ "jest", "browser", "nodejs" ]
  plugins = ["vue"]
  style_guide = "standard"
  module_system = "commonjs"
  dependency_file_paths = [ "package.json" ]
  ecma_version = "2020"
